### PR TITLE
Bump debian package version to 2.0-1

### LINKED ISSUE #159: Bumped debian version to 2.1.0
@rmescandon if you could wave your debian magic wand for 2.1.0 that'd be ace :) 

Changelog:

- Ability to read multiple documents in a single file
- Ability to append list items instead of overwriting

### PR DESCRIPTION
**Pull request by rmescandon**
Here we go.
The package is already available in the ppa.

Aside note: Someday, when I got some spare time I'll investigate how this can be moved to the official Debian repositories (never published anything there before). That would be nice not having to add the PPA to have the package available :)

Fixes #159

### CODE REVIEW

**Comment by mikefarah** [comment]
Hey thanks - but the version string is '2.0-1'? Is that like a wildcard thing or a typo?

**Comment by mikefarah** [comment]
No worries - enjoy you holiday!

**Comment by rmescandon** [comment]
Nah, I cannot leave this abandoned for such a long period. Pushed the change here. In some minutes will the deb repo be updated

**Comment by mikefarah** [comment]
you're a champ :)

**Pull request merged**
