### PR TITLE
bash completion for yq read; requires jq

### PR DESCRIPTION
**Pull request by amkhlv**
Dear Mike, thank you for this excellent tool ! I wrote a bash TAB-completion script for `yq read`. Would you consider adding it to "utils" section?

### CODE REVIEW

**Comment by mikefarah** [comment]
Glad you like it - under the hood, for CLI processing, this uses sp13/cobra, and that has a bash completion feature that would be nice to add:

https://github.com/spf13/cobra/blob/master/bash_completions.md

This also has support for zsh and fish.

**Comment by mikefarah** [comment]
I've implemented the functionality out of cobra, thanks for the idea though 👍

**Comment by mikefarah** [comment]
I should add - check out the latest version (3.3.1) and the shell-completion command :)

**Comment by amkhlv** [comment]
thank you !

**Pull request closed without merging**
