### PR TITLE
#20 Read the top level keys only

### PR DESCRIPTION
**Pull request by RyanSiu1995**

### CODE REVIEW

**Comment by mikefarah** [comment]
Cheers @rmescandon  - v3 now supports this functionality

**Comment by oponder** [comment]
Hi! Thank you for adding this!

Any example for how to use this new flag? 

By the way, I'm trying it out from the `3.0.0-beta` tagged docker image, maybe I was wrong in assuming the new flag would be there:

```
docker run -v ${PWD}:/workdir --rm mikefarah/yq:3.0.0-beta yq r docker-compose.yaml 'services' -k

2020/01/13 17:34:52 unknown shorthand flag: 'k' in -k
Error: unknown shorthand flag: 'k' in -k
```

**Comment by RyanSiu1995** [comment]
Hi @oponder, this pull request has been merged into master branch instead of v3 branch.
You can use the master branch, which is v2 instead.
If you want to use v3, please try this.
```
docker run -v ${PWD}:/workdir --rm mikefarah/yq:3.0.0-beta yq r docker-compose.yaml 'services' -p v
```

**Comment by mikefarah** [comment]
it's the '-p' print mode flag you can see in the command help text, 

v is values, default, p is paths (e.g. a.b[0].c), or you can do both (vp)

**Pull request merged**
