### PR TITLE
Make checksums file usable by common tools

### PR DESCRIPTION
**Pull request by viq**
Adding flag --bsd makes rhash output checksums in a format compatible with common tools, like sha256sum, and makes it obvious what algorithm a particular checksum was calculated for, at the expense of making the checksums file larger. This allows for the checksums file to be used directly by tools understanding traditional format, like Ansible or Salt, and  obviates the existence of extract-checksum.sh script.

### CODE REVIEW

**Comment by viq** [comment]
Comparison:
```
rhash -a yq_linux_amd64.tar.gz 
yq_linux_amd64.tar.gz  c66ab000  8dedb4263a9bb7ec92eb4e60516c7120  03d1a2c04eb4e568f0a342cadbc3e379  8d28cd5ff37166ba495e1adc30615076415d2bc2  45a090656debb161a01e23653b4e3fadcdf9be82c27e0476  d4ufhrjxt53ikf46zpgmwyv3qedgir2yhor5vwi  1e3e21d518a104c9a58387952be907cea0995fed  8dedb4263a9bb7ec92eb4e60516c7120  63ieyp7gpfeeutja2lw77k6mxw4c6arj  2239950138f3ea9785830ee1addc5a660733ad859beee37d87bb554a589beb016746f87f982461d4f99499829a79fb043d4f4e44304c446d1100e92b0829c93c  97f23b8e954c7b22ce32a4a560b4b20b02c9a375  79a9ebd42b23959813f4b212412c8cd116c02743eff021ce6935eb5db99d14be  10402ed45e5fc53f60f0ad27b242305c4e04425faf449cc18d156876a2a5f07e  7b90258842e2e3ccc694fcd5cf409364f8160ba7  64c45077eaf55537f7a35f5c36d5ca0dd21e7e5a20a7f0e5ad2af21bb32979a8  d51611ffda59742e16b71a7e7e7ae42a35fcd1530401326d9310e414ada88ae3d38e3b55c78808c2ce1076a0e0256fe2d95139595bf83a64706ece8b0c6d77e6  279b2e0b02ef4e0f8647da7334ea608ead920b9ce3b9e2b6bc2eaf0b  df8b1ea3ebd84bac31691e5b77b87c798f64c845370593e56603b9892cea3e1c  902a7461bacd9616f8d9e43b73fcb0c87285b12bac79883b92e75c6b0d82f661266d7c9f94371d4b5f872042a0bf23d5  64fb799a01d2ee313e6dfe7b6ee94dacd160948ae9d5b9fec2fce9bcc06a1a1e7abc44f96b916ac01d084fbb75e74a24f66bd43bf8aaaf54a82ecba82617be38  82051112c32b4e9093ce8af6903e72e79701bc1728065aaa0f1c1d9c1d5fb711  fc7bb3c555f0292acc1478f092c480a4b8ab6c1f1696a21f7bef8ea1ccb80deaf91d1b571c907d5f5b3b060536bd8bda637ea0a393be90fee607811c04ad2cbf  2f59425163969484d342e4440221222773e8c11a821daedca11a525b  02bb59ce81206249441e178c33c4e596fcd228ed7fc838b9d0d41e89dac7304e  6ab5632e014a06308ebc2a7bc79f48ff181e4884d73c53d977575be74d509341b15b21c1b59773410dfec44455af0fc7  0645099f6587c3bf9c65f98cdae8e1f98e500748910a3c53eedf2d6fe0d85066e697393709e4738d5d800a05f19ea2cde180c7f97da4644f164ccf4241591711  08ef4bee  8256cc342a10d6388e7ec1fd6ba62371  6b3c23270e6498e914ef84ddfabcac2ccb36d5e8a2d44a3af4d5a71765dd5238  2874976b7e4357d09a2e50524aedb84abdcd296e9fd6cf855cc4bc931a99a203  b8fae87c5a7ecbcb08643684628b24c6971b8b385b6261d67826dfb1a1acf57a6b7e1ac8171a14a560ddd4702796c6bec5f4fb32eaa3d19f032cafd27c2c847e
```
versus
```
rhash -a --bsd yq_linux_amd64.tar.gz 
CRC32 (yq_linux_amd64.tar.gz) = c66ab000
MD4   (yq_linux_amd64.tar.gz) = 8dedb4263a9bb7ec92eb4e60516c7120
MD5   (yq_linux_amd64.tar.gz) = 03d1a2c04eb4e568f0a342cadbc3e379
SHA1  (yq_linux_amd64.tar.gz) = 8d28cd5ff37166ba495e1adc30615076415d2bc2
TIGER (yq_linux_amd64.tar.gz) = 45a090656debb161a01e23653b4e3fadcdf9be82c27e0476
TTH   (yq_linux_amd64.tar.gz) = d4ufhrjxt53ikf46zpgmwyv3qedgir2yhor5vwi
BTIH  (yq_linux_amd64.tar.gz) = 1e3e21d518a104c9a58387952be907cea0995fed
ED2K  (yq_linux_amd64.tar.gz) = 8dedb4263a9bb7ec92eb4e60516c7120
AICH  (yq_linux_amd64.tar.gz) = 63ieyp7gpfeeutja2lw77k6mxw4c6arj
WHIRLPOOL (yq_linux_amd64.tar.gz) = 2239950138f3ea9785830ee1addc5a660733ad859beee37d87bb554a589beb016746f87f982461d4f99499829a79fb043d4f4e44304c446d1100e92b0829c93c
RMD160 (yq_linux_amd64.tar.gz) = 97f23b8e954c7b22ce32a4a560b4b20b02c9a375
GOST94 (yq_linux_amd64.tar.gz) = 79a9ebd42b23959813f4b212412c8cd116c02743eff021ce6935eb5db99d14be
GOST94-CRYPTOPRO (yq_linux_amd64.tar.gz) = 10402ed45e5fc53f60f0ad27b242305c4e04425faf449cc18d156876a2a5f07e
HAS-160 (yq_linux_amd64.tar.gz) = 7b90258842e2e3ccc694fcd5cf409364f8160ba7
GOST12-256 (yq_linux_amd64.tar.gz) = 64c45077eaf55537f7a35f5c36d5ca0dd21e7e5a20a7f0e5ad2af21bb32979a8
GOST12-512 (yq_linux_amd64.tar.gz) = d51611ffda59742e16b71a7e7e7ae42a35fcd1530401326d9310e414ada88ae3d38e3b55c78808c2ce1076a0e0256fe2d95139595bf83a64706ece8b0c6d77e6
SHA224 (yq_linux_amd64.tar.gz) = 279b2e0b02ef4e0f8647da7334ea608ead920b9ce3b9e2b6bc2eaf0b
SHA256 (yq_linux_amd64.tar.gz) = df8b1ea3ebd84bac31691e5b77b87c798f64c845370593e56603b9892cea3e1c
SHA384 (yq_linux_amd64.tar.gz) = 902a7461bacd9616f8d9e43b73fcb0c87285b12bac79883b92e75c6b0d82f661266d7c9f94371d4b5f872042a0bf23d5
SHA512 (yq_linux_amd64.tar.gz) = 64fb799a01d2ee313e6dfe7b6ee94dacd160948ae9d5b9fec2fce9bcc06a1a1e7abc44f96b916ac01d084fbb75e74a24f66bd43bf8aaaf54a82ecba82617be38
EDON-R256 (yq_linux_amd64.tar.gz) = 82051112c32b4e9093ce8af6903e72e79701bc1728065aaa0f1c1d9c1d5fb711
EDON-R512 (yq_linux_amd64.tar.gz) = fc7bb3c555f0292acc1478f092c480a4b8ab6c1f1696a21f7bef8ea1ccb80deaf91d1b571c907d5f5b3b060536bd8bda637ea0a393be90fee607811c04ad2cbf
SHA3-224 (yq_linux_amd64.tar.gz) = 2f59425163969484d342e4440221222773e8c11a821daedca11a525b
SHA3-256 (yq_linux_amd64.tar.gz) = 02bb59ce81206249441e178c33c4e596fcd228ed7fc838b9d0d41e89dac7304e
SHA3-384 (yq_linux_amd64.tar.gz) = 6ab5632e014a06308ebc2a7bc79f48ff181e4884d73c53d977575be74d509341b15b21c1b59773410dfec44455af0fc7
SHA3-512 (yq_linux_amd64.tar.gz) = 0645099f6587c3bf9c65f98cdae8e1f98e500748910a3c53eedf2d6fe0d85066e697393709e4738d5d800a05f19ea2cde180c7f97da4644f164ccf4241591711
CRC32C (yq_linux_amd64.tar.gz) = 08ef4bee
SNEFRU-128 (yq_linux_amd64.tar.gz) = 8256cc342a10d6388e7ec1fd6ba62371
SNEFRU-256 (yq_linux_amd64.tar.gz) = 6b3c23270e6498e914ef84ddfabcac2ccb36d5e8a2d44a3af4d5a71765dd5238
BLAKE2s (yq_linux_amd64.tar.gz) = 2874976b7e4357d09a2e50524aedb84abdcd296e9fd6cf855cc4bc931a99a203
BLAKE2b (yq_linux_amd64.tar.gz) = b8fae87c5a7ecbcb08643684628b24c6971b8b385b6261d67826dfb1a1acf57a6b7e1ac8171a14a560ddd4702796c6bec5f4fb32eaa3d19f032cafd27c2c847e
```
and with contents put in `rhash.normal` and `rhash.bsd`, respectively:
```
echo NORMAL ; sha256sum -c rhash.normal ; echo $? ; echo BSD ; sha256sum -c rhash.bsd ; echo $?
NORMAL
sha256sum: rhash.normal: no properly formatted checksum lines found
1
BSD
yq_linux_amd64.tar.gz: OK
sha256sum: WARNING: 30 lines are improperly formatted
0
```

**Comment by maeve** [comment]
Another vote to please consider merging this PR. 🙏 Our organization would like to use yq, but the extract-checksums.sh script is a complete blocker from a security perspective.

**Comment by mikefarah** [comment]
I'll add that bsd checksum as another file in the release, but won't replace what it currently does as that's a backward breaking change.

**Comment by mikefarah** [comment]
Just trying it out, `rhash -r -a --bsd . -o checksums` will still create a line for each file in the release (e.g. linux amd64, linux mips...), how can sha256 be used to validate the checksum for a single file from the checksum file that contains checksums for all the files?

**Comment by viq** [comment]
> I'll add that bsd checksum as another file in the release, but won't replace what it currently does as that's a backward breaking change.

Great, that certainly works for me :)

> how can sha256 be used to validate the checksum for a single file from the checksum file that contains checksums for all the files?

I'm not sure what the proper answer from terminal is, but given for example
```
curl -JL https://github.com/derailed/k9s/releases/download/v0.27.4/checksums.txt
05f7b054b2f41a69f13893ec819a8aca43662a4bad61951e9887a6f92ecbf2d8  k9s_Linux_arm64.tar.gz
0d3669fd26a6f37aaa5aaeb2166ceab697fb56da43f6870d4480dc3a058ad845  k9s_Windows_arm.zip
5a85fbf6f1a93ae5416327dea0f13aca8a56d9cf796387da2d0fdb6a14ae8360  k9s_Linux_s390x.tar.gz
7a8d0da4e2fff6ff661df6e51d0bd4a3a757e12096028572e83e485724be0c15  k9s_Darwin_amd64.tar.gz
7e10583c66ad5fa1de9f98f3de5e94f3348cbe52f7f8d3d89cc295dd3d6c2d77  k9s_Windows_amd64.zip
8890d5f3453d498dd8bdecc3ec41e529e1d5e80d354be51457682634ead90ec2  k9s_Windows_arm64.zip
9d0e39465f6778cdb270be145dc186387a95811279554976a2bd7d22a854432a  k9s_Linux_ppc64le.tar.gz
9ebae81b7e93f5b438fd666a789f8554e5e576e2c7d7f5529f3770a4439ff9b4  k9s_Linux_arm.tar.gz
cee530dae7dd6987b7bafea1ce2fa778b32d654f8553db100b34a10b065f6889  k9s_Darwin_arm64.tar.gz
e507831ebd5f9b8c0380f212669f352c6e34cb760c916b498babae8be83c4392  k9s_Linux_amd64.tar.gz
```
using it in tools (in this example saltstack) like
```yaml
k9s:
  file.managed:
    - name: /usr/local/k9s/download/k9s-v{{k9s_version}}-linux-amd64.tar.gz
    - source: https://github.com/derailed/k9s/releases/download/v{{k9s_version}}/k9s_Linux_amd64.tar.gz
    - source_hash: https://github.com/derailed/k9s/releases/download/v{{k9s_version}}/checksums.txt
```
works just fine, and ansible is able to use it that way as well - whereas it's not possible to use with current checksum format.

**Comment by mikefarah** [comment]
Released in 4.35.1 as checksums-bsd

**Pull request closed without merging**
