### PR TITLE
Support for Go Modules.

### PR DESCRIPTION
**Pull request by udhos**
Adds support for Go Modules to 'yq' repo.
Fixes https://github.com/mikefarah/yq/issues/227
Depends on https://github.com/mikefarah/yaml/pull/2

### CODE REVIEW

**Comment by mikefarah** [comment]
Merged the  mikefarah/yaml#2 branch, but I can't get this to build locally

```bash
GO111MODULE=on go build
go: gopkg.in/mikefarah/yaml.v2@v2.3.0: parsing go.mod: unexpected module path "gopkg.in/yaml.v2"
go: error loading module requirements
```

It also fails the travis build...

**Comment by udhos** [comment]
Can you check if this PR https://github.com/mikefarah/yaml/pull/3 improves things?

**Comment by mikefarah** [comment]
Exact same error *shrug*

**Comment by udhos** [comment]
Please try merging https://github.com/mikefarah/yaml/pull/4 and then testing this PR locally.
It worked for me with `replace github.com/mikefarah/yaml => github.com/udhos/yaml v0.0.0-20190408152634-649037afe55b` in go.mod.

**Comment by mikefarah** [comment]
This has been fixed with https://github.com/mikefarah/yq/pull/288 :)

**Pull request closed without merging**
